added band gap (orbital) as training label and corresponding test case.
deepmodeling/deepks-kit pull request #12
Opened 2021-11-30 08:04 UTC by ouqi0711

Merge the related code with band gap (orbital) label and corresponding test cases to bandgap branch.

2021-12-02 04:42 UTC, y1xiaoc requested changes
Thanks! It's a great PR! I only have several minor comments. Please see below.

2021-12-02 04:42 UTC, y1xiaoc commented on deepks/scf/scf.py
> +def t_batch_jacobian(f, x, noutputs):
there is a function with same name at line 80. Is this a duplicated one?

2021-12-02 04:42 UTC, y1xiaoc commented on deepks/scf/scf.py
> +    def orbital0(self):
the naming convention is that `xxx0` correspond to the unmodified `xxx` method. Maybe you would like to rename it to `mo_energy0` and add `@property` decorator?

2021-12-02 04:42 UTC, y1xiaoc commented on deepks/scf/scf.py
> +        tic = (time.clock(), time.perf_counter())
Please avoid using `clock()` method, which has been removed in python 3.8. The newest commit in the master branch fixed it.

2021-12-02 04:42 UTC, y1xiaoc commented on deepks/scf/stats.py
> +                ro1 = torch.tensor([myc,1])
can we avoid torch and use pure numpy? This file is intended to be pure numpy.

2021-12-02 04:42 UTC, y1xiaoc commented on deepks/scf/stats.py
> +import torch
I intentionally avoid importing torch in this file to speed up the importing procedure. Can we avoid using torch?

2021-12-06 06:49 UTC, ouqi0711 commented on deepks/scf/scf.py
> +def t_batch_jacobian(f, x, noutputs):
Yes and sorry. The one at line 46 has now been removed.

2021-12-06 06:52 UTC, ouqi0711 commented on deepks/scf/scf.py
> +        tic = (time.clock(), time.perf_counter())
Thanks and this has been fixed.

2021-12-06 08:09 UTC, ouqi0711 commented on deepks/scf/stats.py
> +                ro1 = torch.tensor([myc,1])
Yes, I've changed these to numpy operations.

2021-12-06 08:09 UTC, ouqi0711 commented on deepks/scf/stats.py
> +import torch
Yes, line 5 has been removed.

2021-12-06 08:30 UTC, ouqi0711 commented on deepks/scf/scf.py
> +    def orbital0(self):
Sure, I've changed orbital0 to mo_energy0 throughout the scripts and seems working fine.

2021-12-06 08:41 UTC, ouqi0711 commented
All fixes have been pushed to the master branch on ouqi0711/deepks-kit.

2021-12-09 05:47 UTC, merged