Support submitting jobs by DPDispatcher
deepmodeling/deepks-kit pull request #31
Opened 2022-08-17 13:28 UTC by maki49

I put the DPDispatcher interface into class `GroupBatchTask`. 
Tests on case `examples/water_single_lda2pbe_abacus/iter/` have been passed with both lazylocalcontext and on Bohrium(Lebesguecontext). Input files and README of this example are also updated.

Sometimes the `model.pth` trained on Lebesgue has a parameter `elem_table`, it seems useless. I add this parameter in class `CorrNet` just to correctly load the model.

2022-08-17 18:22 UTC, y1xiaoc requested changes
Very nice work and thanks a lot for the contribution! 

Most of the code is pretty good. Apart from the comment I have two major concerns:

1. The `elem_table` parameter you added does actually play some role and was already added in the [develop branch](https://github.com/deepmodeling/deepks-kit/blob/develop/deepks/model/model.py#L218). It seems that abacus branch has not been updated with develop branch for a while. Maybe consider do two separate PR? The first one is to merge the develop branch to abacus, and the second one is the current dpdispatcher integration that based on the merged branch.
2. Since dpdispatcher use its own task list, resources and machines, etc., it seems not a good idea to add it as an option in GroupBatchTask. Maybe we could directly add a new task class called `DPDispatcherTask`? In that case, the modification of current code might be easier (for example several parameters could be reused?). (I'm also wondering is it possible to generate dpdispatcher task lists from current Batched task?)

2022-08-17 18:22 UTC, y1xiaoc commented on deepks/iterate/template_abacus.py
> +        return BatchTask(
Here dpdispatcher separate the task by each frame, but old version only use a single Batch task. Can it be separated as well? In that case it would also better match the original pyscf scf task structure.

2022-08-17 19:51 UTC, njzjz commented on deepks/iterate/template.py
> +}
Neither of these arguments is valid.

2022-08-18 08:48 UTC, maki49 commented on deepks/iterate/template_abacus.py
> +        return BatchTask(
It's not possible to generate dpdispatcher task_lists by BatchTask objects, because dpdispatcher have its own `Task` class which has some interfaces not in BatchTask. 
But It's not difficult to write a new class `DPDispatcherTask`.I'll do it in the next commit.

2022-08-18 09:02 UTC, maki49 commented on deepks/iterate/template_abacus.py
> +        return BatchTask(
> Here dpdispatcher separate the task by each frame, but old version only use a single Batch task. Can it be separated as well? In that case it would also better match the original pyscf scf task structure.

I've separated them in commit [19cee06](https://github.com/deepmodeling/deepks-kit/pull/31/commits/19cee06ba7258eb95c09c5f092dfda5d67216207). Now `sub_size` is an invalid parameter when using ABACUS, because the `command` of each BatchTask would be a loop when `sub_size`>1, which is too combersome. (For parallel computing between different frames, is `group_size` enough? )

2022-08-18 12:34 UTC, maki49 commented on deepks/iterate/template.py
> +}
Thanks for pointing it out. I've fixed it in commit [8bc4095](https://github.com/deepmodeling/deepks-kit/pull/31/commits/8bc4095ccb7308db794950909b05b32bd0aec774).

2022-08-18 18:57 UTC, y1xiaoc approved these changes

2022-08-18 18:57 UTC, merged